spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sz_1904?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8888
logging:
  level:
    com.qianfeng.springbootmybatis.controller.UserController : debug